sudo: false
language: cpp
env:
  global:
    - PYTHON_PACKAGES="pip setuptools pytest cffi pep8 cpp-coveralls"
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - valgrind
      - cmake
      - libblas-dev
      - libblas3gf
before_install:
  - if test ${TRAVIS_OS_NAME} = osx; then brew update; fi
  - if test ${TRAVIS_OS_NAME} = osx; then brew outdated xctool || brew upgrade xctool; fi
  - if test ${TRAVIS_OS_NAME} = osx; then brew unlink gcc; fi
  - if test ${TRAVIS_OS_NAME} = osx; then brew install python valgrind gcc; fi
  - if test ${TRAVIS_OS_NAME} = osx; then brew linkapps python; fi
before_script:
  - export PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:$PATH
  - if test ${TRAVIS_OS_NAME} = linux;
    then pip install --upgrade ${PYTHON_PACKAGES} --user `whoami`;
    else sudo pip install --upgrade ${PYTHON_PACKAGES}; fi
script:
  - if test ${TRAVIS_OS_NAME} = linux; then python setup.py --cc=gcc --cxx=g++ --fc=gfortran-4.9 --coverage --type=debug;
                                       else python setup.py --cc=gcc --cxx=g++ --fc=gfortran --coverage --type=debug; fi
  - cd build
  - make
  - make test
  - cd ..
  - pep8 --ignore=E501 test/test.py
  - py.test -vv test/test.py build
after_success:
  - coveralls -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E ".*src/lebedev/.*.cpp.*"
